Repository AY2021S1-CS2103-T14-3/tp, pull requests merged in 2020-10, with the labels that each got.

#55 Add Activity Class and abstract common classes into a package
  src/main/java/seedu/address/model/activity/Activity.java
  src/main/java/seedu/address/model/activity/Importance.java
  src/main/java/seedu/address/model/activity/UniqueActivityList.java
  src/main/java/seedu/address/model/activity/exceptions/ActivityNotFoundException.java
  src/main/java/seedu/address/model/activity/exceptions/DuplicateActivityException.java
  src/main/java/seedu/address/model/commons/Cost.java
  src/main/java/seedu/address/model/commons/Location.java
  src/main/java/seedu/address/model/commons/Name.java
  src/main/java/seedu/address/model/commons/NameContainsKeywordsPredicate.java
Labels: priority.High

#59 Add TravelPlan Package with TravelPlan and Wishlist Class
  src/main/java/seedu/address/model/accommodation/Accommodation.java
  src/main/java/seedu/address/model/activity/Activity.java
  src/main/java/seedu/address/model/activity/UniqueActivityList.java
  src/main/java/seedu/address/model/commons/ReadOnlyActivityList.java
  src/main/java/seedu/address/model/commons/WanderlustDate.java
  src/main/java/seedu/address/model/friend/Friend.java
  src/main/java/seedu/address/model/travelplan/AccommodationList.java
  src/main/java/seedu/address/model/travelplan/ActivityList.java
  src/main/java/seedu/address/model/travelplan/FriendList.java
  src/main/java/seedu/address/model/travelplan/ReadOnlyAccommodationList.java
  src/main/java/seedu/address/model/travelplan/ReadOnlyFriendList.java
  src/main/java/seedu/address/model/travelplan/TravelPlan.java
  src/main/java/seedu/address/model/travelplan/TravelPlanObject.java
  src/main/java/seedu/address/model/wishlist/Wishlist.java
Labels: priority.High

#80 Update model manager
  src/main/java/seedu/address/model/activity/UniqueActivityList.java
  src/main/java/seedu/address/model/travelplan/TravelPlan.java
  src/main/java/seedu/address/model/travelplanner/Directory.java
  src/main/java/seedu/address/model/travelplanner/Model.java
  src/main/java/seedu/address/model/travelplanner/ModelManager.java
  src/main/java/seedu/address/model/travelplanner/TravelPlanner.java
Labels: need help

#100 GoTo Command and GoTo Command Test
  src/main/java/seedu/address/logic/wanderlustlogic/wanderlustcommands/EditCommand.java
  src/main/java/seedu/address/logic/wanderlustlogic/wanderlustcommands/GoToCommand.java
  src/main/java/seedu/address/logic/wanderlustlogic/wanderlustparser/WanderlustGoToCommandParser.java
  src/main/java/seedu/address/logic/wanderlustlogic/wanderlustparser/WanderlustParser.java
  src/main/java/seedu/address/model/travelplanner/Model.java
  src/main/java/seedu/address/model/travelplanner/ModelManager.java
  src/main/java/seedu/address/ui/TravelPlanPanel.java
  src/test/java/seedu/address/logic/commands/GoToCommandTest.java
Labels: priority.High

#102 Update parser
  src/main/java/seedu/address/logic/wanderlustlogic/wanderlustcommands/Command.java
  src/main/java/seedu/address/logic/wanderlustlogic/wanderlustparser/WanderlustParser.java
Labels: priority.Low

#131 Help command
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/java/seedu/address/logic/wanderlustlogic/wanderlustcommands/delete/DeleteActivityCommandTest.java
  src/test/java/seedu/address/logic/wanderlustlogic/wanderlustcommands/edit/EditActivityCommandTest.java
Labels: priority.Low

#134 Refine java doc
  src/main/java/seedu/address/logic/wanderlustlogic/Logic.java
  src/main/java/seedu/address/logic/wanderlustlogic/wanderlustcommands/ExitCommand.java
  src/main/java/seedu/address/logic/wanderlustlogic/wanderlustcommands/GoToCommand.java
  src/main/java/seedu/address/logic/wanderlustlogic/wanderlustcommands/delete/DeleteAccommodationCommand.java
  src/main/java/seedu/address/logic/wanderlustlogic/wanderlustcommands/delete/DeleteActivityCommand.java
  src/main/java/seedu/address/logic/wanderlustlogic/wanderlustcommands/delete/DeleteFriendCommand.java
  src/main/java/seedu/address/logic/wanderlustlogic/wanderlustcommands/delete/DeleteTravelPlanCommand.java
  src/main/java/seedu/address/logic/wanderlustlogic/wanderlustparser/CliSyntax.java
  src/main/java/seedu/address/logic/wanderlustlogic/wanderlustparser/Prefix.java
  src/main/java/seedu/address/logic/wanderlustlogic/wanderlustparser/WanderlustGoToCommandParser.java
  src/main/java/seedu/address/logic/wanderlustlogic/wanderlustparser/WanderlustParser.java
  src/main/java/seedu/address/model/activity/UniqueActivityList.java
  src/main/java/seedu/address/model/activity/WanderlustDateTime.java
  src/main/java/seedu/address/model/commons/Location.java
  src/main/java/seedu/address/model/commons/WanderlustDate.java
Labels: priority.Low

#139 [DG] Implementation for GoTo Command
  docs/DeveloperGuide.md
  docs/GoToUiClassDiagram.png
  docs/diagrams/GoToUiActivityDiagram.puml
  docs/diagrams/GoToUiClassDiagram.puml
  docs/diagrams/GoToUiSequenceDiagram.puml
  docs/images/GoToUiActivityDiagram.png
  docs/images/GoToUiClassDiagram.png
  docs/images/GoToUiSequenceDiagram.png
Labels: priority.Medium

#141 Update DG: Find
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/DGFindCommandClassDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/FindActivityDiagram.puml
  docs/diagrams/FindSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/DGFindCommandClassDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/FindActivityDiagram.png
  docs/images/FindSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
Labels: need help

#158 Sort command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/command/sort/SortAccommodationCommand.java
  src/main/java/seedu/address/logic/command/sort/SortActivityCommand.java
  src/main/java/seedu/address/logic/command/sort/SortCommand.java
  src/main/java/seedu/address/logic/command/sort/SortFriendCommand.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/logic/parser/WanderlustParser.java
  src/main/java/seedu/address/model/Directory.java
  src/main/java/seedu/address/model/accommodation/Accommodation.java
  src/main/java/seedu/address/model/accommodation/UniqueAccommodationList.java
  src/main/java/seedu/address/model/activity/Activity.java
  src/main/java/seedu/address/model/activity/Importance.java
  src/main/java/seedu/address/model/activity/UniqueActivityList.java
  src/main/java/seedu/address/model/activity/WanderlustDateTime.java
  src/main/java/seedu/address/model/commons/Cost.java
  src/main/java/seedu/address/model/friend/Friend.java
  src/main/java/seedu/address/model/friend/UniqueFriendList.java
  src/main/java/seedu/address/model/travelplan/AccommodationList.java
  src/main/java/seedu/address/model/travelplan/ActivityList.java
  src/main/java/seedu/address/model/travelplan/TravelPlan.java
  src/main/java/seedu/address/model/wishlist/Wishlist.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TravelPlanObjectListPanel.java
  src/main/java/seedu/address/ui/TravelPlanPanel.java
  src/main/resources/view/TravelPlanPanel.fxml
Labels: priority.High

#173 [DG] Delete Command
  docs/DeveloperGuide.md
  docs/diagrams/DeleteActivityDiagram.puml
  docs/images/DeleteActivityDiagram.png
Labels: priority.Medium
